auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            pengbing.me
url:              http://pengbing.me
feed:             /atom.xml
author:
    name:         pengbing
description:      "pengbing\'s Blog"
author_info:      <a href="http://pengbing.me/about">pengbing</a>

copyright:
    - Design by <a href="http://pengbing.me/about" title="pengbing" target="_blank">pengbing</a> &copy; Copyright 2012
